import Head from "next/head";
import Link from "next/dist/client/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Max Werner | IDA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="font-bold">Max Werner | IDA</h1>
      <Link href="/process">Process</Link>
    </>
  );
}
